requirements "Requirements" {
  source: "/home/labeth/ws/engineering-model-go/examples/bedrock-pr-review-github-app-sample/generated/lobster/requirements.lobster";
}

activity "Tests" {
  source: "/home/labeth/ws/engineering-model-go/examples/bedrock-pr-review-github-app-sample/generated/lobster/activities.lobster";
  trace to: "Requirements";
}
