inputs:
  - /home/labeth/ws/engineering-model-go/examples/coffee-fleet-ota-cloud-sample/generated/trlc/model.rsl
  - /home/labeth/ws/engineering-model-go/examples/coffee-fleet-ota-cloud-sample/generated/trlc/requirements.trlc
conversion-rules:
  - package: CoffeeFleetRequirements
    record-type: Requirement
    namespace: req
    description-fields:
      - text
