requirements "Requirements" {
  source: "examples/coffee-fleet-ota-cloud-sample/generated/lobster/requirements.lobster";
}

activity "Tests" {
  source: "examples/coffee-fleet-ota-cloud-sample/generated/lobster/activities.lobster";
  trace to: "Requirements";
}
