requirements "Requirements" {
  source: "/home/labeth/ws/engineering-model-go/examples/coffee-fleet-ota-cloud-sample/generated/lobster/requirements.lobster";
}

activity "Tests" {
  source: "/home/labeth/ws/engineering-model-go/examples/coffee-fleet-ota-cloud-sample/generated/lobster/activities.lobster";
  trace to: "Requirements";
}
