apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: payments-sample-source
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/example/payments-engineering-sample.git
  ref:
    branch: main
