apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-scorer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: risk-scorer
  template:
    metadata:
      labels:
        app: risk-scorer
    spec:
      containers:
        - name: risk-scorer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
