requirements "Requirements" {
  source: "examples/payments-engineering-sample/generated/lobster/requirements.lobster";
}

activity "Tests" {
  source: "examples/payments-engineering-sample/generated/lobster/activities.lobster";
  trace to: "Requirements";
}
